// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"shopx/internal/dao/internal"
)

// accountUserBaseDao is the data access object for the table account_user_base.
// You can define custom methods on it to extend its functionality as needed.
type accountUserBaseDao struct {
	*internal.AccountUserBaseDao
}

var (
	// AccountUserBase is a globally accessible object for table account_user_base operations.
	AccountUserBase = accountUserBaseDao{internal.NewAccountUserBaseDao()}
)

// Add your custom methods and functionality below.
