// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameAccountUserGroupRel = "account_user_group_rel"

// AccountUserGroupRel 好友组关系
type AccountUserGroupRel struct {
	GroupRelID int32 `gorm:"column:group_rel_id;primaryKey;autoIncrement:true;comment:好友组编号" json:"group_rel_id"` // 好友组编号
	GroupID    int32 `gorm:"column:group_id;not null;comment:组名称" json:"group_id"`                                // 组名称
	UserID     int32 `gorm:"column:user_id;not null;comment:用户" json:"user_id"`                                   // 用户
}

// TableName AccountUserGroupRel's table name
func (*AccountUserGroupRel) TableName() string {
	return TableNameAccountUserGroupRel
}
