// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameAccountUserZoneRel = "account_user_zone_rel"

// AccountUserZoneRel 群组用户关系表
type AccountUserZoneRel struct {
	ZoneRelID         int32 `gorm:"column:zone_rel_id;primaryKey;autoIncrement:true;comment:关系编号" json:"zone_rel_id"`                  // 关系编号
	ZoneID            int32 `gorm:"column:zone_id;not null;comment:群组编号" json:"zone_id"`                                               // 群组编号
	UserID            int32 `gorm:"column:user_id;not null;comment:用户" json:"user_id"`                                                 // 用户
	ZoneRelPermission int32 `gorm:"column:zone_rel_permission;not null;comment:申请加入模式(ENUM): 0-加入; 1-待验证;" json:"zone_rel_permission"` // 申请加入模式(ENUM): 0-加入; 1-待验证;
}

// TableName AccountUserZoneRel's table name
func (*AccountUserZoneRel) TableName() string {
	return TableNameAccountUserZoneRel
}
