// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameAccountUserDeliveryAddress = "account_user_delivery_address"

// AccountUserDeliveryAddress 用户地址表
type AccountUserDeliveryAddress struct {
	UdID         int32     `gorm:"column:ud_id;primaryKey;autoIncrement:true;comment:地址编号" json:"ud_id"`                          // 地址编号
	UserID       int32     `gorm:"column:user_id;not null;comment:用户编号" json:"user_id"`                                           // 用户编号
	UdName       string    `gorm:"column:ud_name;not null;comment:联系人" json:"ud_name"`                                            // 联系人
	UdIntl       string    `gorm:"column:ud_intl;not null;default:+86;comment:国家编码" json:"ud_intl"`                               // 国家编码
	UdMobile     string    `gorm:"column:ud_mobile;not null;comment:手机号码" json:"ud_mobile"`                                       // 手机号码
	UdTelephone  string    `gorm:"column:ud_telephone;not null;comment:联系电话" json:"ud_telephone"`                                 // 联系电话
	UdProvinceID int32     `gorm:"column:ud_province_id;not null;comment:省编号" json:"ud_province_id"`                              // 省编号
	UdProvince   string    `gorm:"column:ud_province;not null;comment:省份" json:"ud_province"`                                     // 省份
	UdCityID     int32     `gorm:"column:ud_city_id;not null;comment:市编号" json:"ud_city_id"`                                      // 市编号
	UdCity       string    `gorm:"column:ud_city;not null;comment:市" json:"ud_city"`                                              // 市
	UdCountyID   int32     `gorm:"column:ud_county_id;not null;comment:县" json:"ud_county_id"`                                    // 县
	UdCounty     string    `gorm:"column:ud_county;not null;comment:县区" json:"ud_county"`                                         // 县区
	UdAddress    string    `gorm:"column:ud_address;not null;comment:详细地址" json:"ud_address"`                                     // 详细地址
	UdPostalcode string    `gorm:"column:ud_postalcode;not null;comment:邮政编码" json:"ud_postalcode"`                               // 邮政编码
	UdTagName    string    `gorm:"column:ud_tag_name;not null;comment:地址标签(ENUM):1001-家里;1002-公司" json:"ud_tag_name"`             // 地址标签(ENUM):1001-家里;1002-公司
	UdLongitude  float64   `gorm:"column:ud_longitude;not null;comment:经度" json:"ud_longitude"`                                   // 经度
	UdLatitude   float64   `gorm:"column:ud_latitude;not null;comment:纬读" json:"ud_latitude"`                                     // 纬读
	UdTime       time.Time `gorm:"column:ud_time;not null;default:CURRENT_TIMESTAMP;comment:添加时间" json:"ud_time"`                 // 添加时间
	UdIsDefault  []uint8   `gorm:"column:ud_is_default;not null;default:b'0';comment:是否默认(BOOL):0-非默认;1-默认" json:"ud_is_default"` // 是否默认(BOOL):0-非默认;1-默认
}

// TableName AccountUserDeliveryAddress's table name
func (*AccountUserDeliveryAddress) TableName() string {
	return TableNameAccountUserDeliveryAddress
}
