// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameAccountUserLoginHistory = "account_user_login_history"

// AccountUserLoginHistory 用户登录信息表
type AccountUserLoginHistory struct {
	UserLoginHistoryID int32   `gorm:"column:user_login_history_id;primaryKey;autoIncrement:true;comment:日志编号" json:"user_login_history_id"`   // 日志编号
	UserID             int32   `gorm:"column:user_id;not null;comment:用户编号" json:"user_id"`                                                    // 用户编号
	UserAccount        string  `gorm:"column:user_account;not null;comment:用户账号" json:"user_account"`                                          // 用户账号
	UserLoginIP        string  `gorm:"column:user_login_ip;not null;comment:登录IP" json:"user_login_ip"`                                        // 登录IP
	UserLoginTime      int64   `gorm:"column:user_login_time;not null;comment:登录时间" json:"user_login_time"`                                    // 登录时间
	UserLoginState     []uint8 `gorm:"column:user_login_state;not null;default:b'1';comment:登录状态(BOOL):0-登录失败;1-登录成功" json:"user_login_state"` // 登录状态(BOOL):0-登录失败;1-登录成功
}

// TableName AccountUserLoginHistory's table name
func (*AccountUserLoginHistory) TableName() string {
	return TableNameAccountUserLoginHistory
}
