// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameAccountUserLevel = "account_user_level"

// AccountUserLevel 用户等级表-平台
type AccountUserLevel struct {
	UserLevelID        int32   `gorm:"column:user_level_id;primaryKey;autoIncrement:true;comment:等级编号" json:"user_level_id"`                       // 等级编号
	UserLevelName      string  `gorm:"column:user_level_name;not null;comment:等级名称" json:"user_level_name"`                                        // 等级名称
	UserLevelExp       int32   `gorm:"column:user_level_exp;not null;comment:升级经验值" json:"user_level_exp"`                                         // 升级经验值
	UserLevelSpend     int32   `gorm:"column:user_level_spend;not null;comment:累计消费" json:"user_level_spend"`                                      // 累计消费
	UserLevelLogo      string  `gorm:"column:user_level_logo;not null;comment:等级图标" json:"user_level_logo"`                                        // 等级图标
	UserLevelRate      int32   `gorm:"column:user_level_rate;not null;comment:折扣率百分比" json:"user_level_rate"`                                      // 折扣率百分比
	UserLevelTime      int64   `gorm:"column:user_level_time;not null;comment:修改时间" json:"user_level_time"`                                        // 修改时间
	UserLevelIsBuildin []uint8 `gorm:"column:user_level_is_buildin;not null;default:b'0';comment:系统内置(BOOL):0-否;1-是" json:"user_level_is_buildin"` // 系统内置(BOOL):0-否;1-是
}

// TableName AccountUserLevel's table name
func (*AccountUserLevel) TableName() string {
	return TableNameAccountUserLevel
}
