// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameAccountUserDistribution = "account_user_distribution"

// AccountUserDistribution 粉丝来源关系表
type AccountUserDistribution struct {
	UserID             int32   `gorm:"column:user_id;primaryKey;autoIncrement:true;comment:用户编号" json:"user_id"`                  // 用户编号
	UserParentID       int32   `gorm:"column:user_parent_id;not null;comment:上级用户编号" json:"user_parent_id"`                       // 上级用户编号
	UserPartnerID      int32   `gorm:"column:user_partner_id;not null;comment:所属城市合伙人" json:"user_partner_id"`                    // 所属城市合伙人
	UserTeamCount      int32   `gorm:"column:user_team_count;not null;comment:团队人数" json:"user_team_count"`                       // 团队人数
	UserProvinceTeamID int32   `gorm:"column:user_province_team_id;not null;comment:所属省公司" json:"user_province_team_id"`          // 所属省公司
	UserCityTeamID     int32   `gorm:"column:user_city_team_id;not null;comment:所属市公司" json:"user_city_team_id"`                  // 所属市公司
	UserCountyTeamID   int32   `gorm:"column:user_county_team_id;not null;comment:所属区公司" json:"user_county_team_id"`              // 所属区公司
	RoleLevelID        int32   `gorm:"column:role_level_id;not null;default:1001;comment:角色等级" json:"role_level_id"`              // 角色等级
	UccID              int32   `gorm:"column:ucc_id;not null;comment:渠道编号" json:"ucc_id"`                                         // 渠道编号
	ActivityID         int32   `gorm:"column:activity_id;not null;comment:活动编号" json:"activity_id"`                               // 活动编号
	UserTime           int64   `gorm:"column:user_time;not null;comment:注册时间" json:"user_time"`                                   // 注册时间
	UserFansNum        int32   `gorm:"column:user_fans_num;not null;comment:粉丝数量:冗余" json:"user_fans_num"`                        // 粉丝数量:冗余
	UserIsSp           []uint8 `gorm:"column:user_is_sp;not null;default:b'0';comment:服务商(BOOL):0-否;1-是;" json:"user_is_sp"`      // 服务商(BOOL):0-否;1-是;
	UserIsDa           int32   `gorm:"column:user_is_da;not null;comment:区代理(BOOL):0-否;1-是为区Id;" json:"user_is_da"`               // 区代理(BOOL):0-否;1-是为区Id;
	UserIsCa           int32   `gorm:"column:user_is_ca;not null;comment:市代理(BOOL):0-否;1-是为市Id;" json:"user_is_ca"`               // 市代理(BOOL):0-否;1-是为市Id;
	UserIsPa           int32   `gorm:"column:user_is_pa;not null;comment:省代理(BOOL):0-否;1-是为省Id;" json:"user_is_pa"`               // 省代理(BOOL):0-否;1-是为省Id;
	UserIsPt           []uint8 `gorm:"column:user_is_pt;not null;default:b'0';comment:城市合伙人(BOOL):0-否;1-是;" json:"user_is_pt"`    // 城市合伙人(BOOL):0-否;1-是;
	UserActive         []uint8 `gorm:"column:user_active;not null;default:b'1';comment:是否有效(BOOL):0-未生效;1-有效" json:"user_active"` // 是否有效(BOOL):0-未生效;1-有效
	UserVoucherIds     string  `gorm:"column:user_voucher_ids;not null;comment:分销优惠券" json:"user_voucher_ids"`                    // 分销优惠券
}

// TableName AccountUserDistribution's table name
func (*AccountUserDistribution) TableName() string {
	return TableNameAccountUserDistribution
}
