// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameAccountUserAnalytic = "account_user_analytics"

// AccountUserAnalytic 用户角色信息表
type AccountUserAnalytic struct {
	UserID               int32   `gorm:"column:user_id;primaryKey;comment:用户编号" json:"user_id"`                               // 用户编号
	UserSpend            float64 `gorm:"column:user_spend;not null;default:0.00;comment:消费总额" json:"user_spend"`              // 消费总额
	UserRefund           float64 `gorm:"column:user_refund;not null;default:0.00;comment:退款总额" json:"user_refund"`            // 退款总额
	UserOrderBuyNum      int32   `gorm:"column:user_order_buy_num;not null;comment:有效订单数量" json:"user_order_buy_num"`         // 有效订单数量
	UserOrderReturnNum   int32   `gorm:"column:user_order_return_num;not null;comment:退单数量" json:"user_order_return_num"`     // 退单数量
	UserProductBuyNum    int32   `gorm:"column:user_product_buy_num;not null;comment:购买数量" json:"user_product_buy_num"`       // 购买数量
	UserProductReturnNum int32   `gorm:"column:user_product_return_num;not null;comment:退货数量" json:"user_product_return_num"` // 退货数量
	Version              int32   `gorm:"column:version;not null;comment:版本" json:"version"`                                   // 版本
}

// TableName AccountUserAnalytic's table name
func (*AccountUserAnalytic) TableName() string {
	return TableNameAccountUserAnalytic
}
