// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameAccountUserZoneMessage = "account_user_zone_message"

// AccountUserZoneMessage 群组消息-聊天记录
type AccountUserZoneMessage struct {
	ZoneMessageID       int32     `gorm:"column:zone_message_id;primaryKey;autoIncrement:true;comment:短消息索引编号" json:"zone_message_id"`                // 短消息索引编号
	UserID              int32     `gorm:"column:user_id;not null;default:1;comment:发送用户" json:"user_id"`                                              // 发送用户
	ZoneID              int32     `gorm:"column:zone_id;not null;comment:群组编号" json:"zone_id"`                                                        // 群组编号
	ZoneMessageContent  string    `gorm:"column:zone_message_content;not null;comment:短消息内容" json:"zone_message_content"`                             // 短消息内容
	ZoneMessageTime     time.Time `gorm:"column:zone_message_time;not null;default:CURRENT_TIMESTAMP;comment:短消息发送时间" json:"zone_message_time"`       // 短消息发送时间
	ZoneMessageIsDelete int32     `gorm:"column:zone_message_is_delete;not null;comment:短消息状态(BOOL):0-正常状态;1-删除状态" json:"zone_message_is_delete"`     // 短消息状态(BOOL):0-正常状态;1-删除状态
	ZoneMessageType     int32     `gorm:"column:zone_message_type;not null;default:2;comment:消息类型(ENUM):1-系统消息;2-用户消息;3-私信" json:"zone_message_type"` // 消息类型(ENUM):1-系统消息;2-用户消息;3-私信
}

// TableName AccountUserZoneMessage's table name
func (*AccountUserZoneMessage) TableName() string {
	return TableNameAccountUserZoneMessage
}
