// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameAccountUserSn = "account_user_sns"

// AccountUserSn 用户SNS信息表
type AccountUserSn struct {
	UserID              int32   `gorm:"column:user_id;primaryKey;comment:用户编号" json:"user_id"`                                           // 用户编号
	UserBlog            int32   `gorm:"column:user_blog;not null;comment:微博数量" json:"user_blog"`                                         // 微博数量
	UserFriend          int32   `gorm:"column:user_friend;not null;comment:好友数量" json:"user_friend"`                                     // 好友数量
	UserFans            int32   `gorm:"column:user_fans;not null;comment:粉丝数量" json:"user_fans"`                                         // 粉丝数量
	UserGrowth          int32   `gorm:"column:user_growth;not null;comment:成长值" json:"user_growth"`                                      // 成长值
	UserReport          []uint8 `gorm:"column:user_report;not null;default:b'1';comment:是否可以举报(BOOL):0-不可以;1-可以" json:"user_report"`     // 是否可以举报(BOOL):0-不可以;1-可以
	UserBuy             []uint8 `gorm:"column:user_buy;not null;default:b'1';comment:是否可以购买商品(BOOL):0-不可以;1-可以" json:"user_buy"`         // 是否可以购买商品(BOOL):0-不可以;1-可以
	UserComment         []uint8 `gorm:"column:user_comment;not null;default:b'1';comment:是否允许发表言论(BOOL):0-不可以;1-可以" json:"user_comment"` // 是否允许发表言论(BOOL):0-不可以;1-可以
	UserFansStore       int32   `gorm:"column:user_fans_store;not null;comment:推广店铺数量" json:"user_fans_store"`                           // 推广店铺数量
	UserStory           int32   `gorm:"column:user_story;not null;comment:帖子数量" json:"user_story"`                                       // 帖子数量
	UserStoryComment    int32   `gorm:"column:user_story_comment;not null;comment:评论数量" json:"user_story_comment"`                       // 评论数量
	UserFavoritesStore  int32   `gorm:"column:user_favorites_store;not null;comment:收藏店铺" json:"user_favorites_store"`                   // 收藏店铺
	UserFavoritesItem   int32   `gorm:"column:user_favorites_item;not null;comment:收藏商品" json:"user_favorites_item"`                     // 收藏商品
	UserFavoritesBrand  int32   `gorm:"column:user_favorites_brand;not null;comment:收藏品牌" json:"user_favorites_brand"`                   // 收藏品牌
	UserStoryCollection int32   `gorm:"column:user_story_collection;not null;comment:收藏帖子" json:"user_story_collection"`                 // 收藏帖子
	UserStoryLike       int32   `gorm:"column:user_story_like;not null;comment:帖子点赞" json:"user_story_like"`                             // 帖子点赞
	UserStoryForward    int32   `gorm:"column:user_story_forward;not null;comment:帖子转发" json:"user_story_forward"`                       // 帖子转发
	Version             int32   `gorm:"column:version;not null;comment:乐观锁" json:"version"`                                              // 乐观锁
}

// TableName AccountUserSn's table name
func (*AccountUserSn) TableName() string {
	return TableNameAccountUserSn
}
