// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameAccountUserChannelCode = "account_user_channel_code"

// AccountUserChannelCode 用户渠道邀请码表
type AccountUserChannelCode struct {
	UccID         int32   `gorm:"column:ucc_id;primaryKey;autoIncrement:true;comment:渠道编号" json:"ucc_id"`                       // 渠道编号
	UccCode       string  `gorm:"column:ucc_code;not null;comment:渠道名称" json:"ucc_code"`                                        // 渠道名称
	UccEnable     []uint8 `gorm:"column:ucc_enable;not null;default:b'1';comment:是否启用(BOOL):0-禁用;1-启用" json:"ucc_enable"`       // 是否启用(BOOL):0-禁用;1-启用
	UserID        int32   `gorm:"column:user_id;not null;comment:会员编号" json:"user_id"`                                          // 会员编号
	UserChannelID int32   `gorm:"column:user_channel_id;not null;comment:渠道编号" json:"user_channel_id"`                          // 渠道编号
	UccUsed       int32   `gorm:"column:ucc_used;not null;comment:是否使用(BOOL):0-未使用;1-已使用" json:"ucc_used"`                      // 是否使用(BOOL):0-未使用;1-已使用
	UccUseTime    int64   `gorm:"column:ucc_use_time;not null;comment:使用时间" json:"ucc_use_time"`                                // 使用时间
	UccCreateTime int64   `gorm:"column:ucc_create_time;not null;comment:创建时间" json:"ucc_create_time"`                          // 创建时间
	UccIsUnique   int32   `gorm:"column:ucc_is_unique;not null;default:1;comment:唯一使用(BOOL):0-不限制;1-可用一次" json:"ucc_is_unique"` // 唯一使用(BOOL):0-不限制;1-可用一次
	UccUseNum     int32   `gorm:"column:ucc_use_num;not null;comment:使用次数" json:"ucc_use_num"`                                  // 使用次数
}

// TableName AccountUserChannelCode's table name
func (*AccountUserChannelCode) TableName() string {
	return TableNameAccountUserChannelCode
}
