// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameAccountUserBindConnect = "account_user_bind_connect"

// AccountUserBindConnect 用户绑定表
type AccountUserBindConnect struct {
	BindID       string    `gorm:"column:bind_id;primaryKey;comment:绑定标记" json:"bind_id"`                                            // 绑定标记
	BindType     int32     `gorm:"column:bind_type;not null;comment:绑定类型(EMUN):1-mobile;  2-email;   13-weixin公众号" json:"bind_type"` // 绑定类型(EMUN):1-mobile;  2-email;   13-weixin公众号
	UserID       int32     `gorm:"column:user_id;not null;comment:用户编号" json:"user_id"`                                              // 用户编号
	BindTime     time.Time `gorm:"column:bind_time;not null;default:CURRENT_TIMESTAMP;comment:绑定时间" json:"bind_time"`                // 绑定时间
	BindNickname string    `gorm:"column:bind_nickname;not null;comment:用户名称" json:"bind_nickname"`                                  // 用户名称
	BindIcon     string    `gorm:"column:bind_icon;not null;comment:用户图标" json:"bind_icon"`                                          // 用户图标
	BindOpenid   string    `gorm:"column:bind_openid;not null;comment:访问编号" json:"bind_openid"`                                      // 访问编号
	BindUnionid  string    `gorm:"column:bind_unionid;not null;comment:unionid" json:"bind_unionid"`                                 // unionid
	BindActive   []uint8   `gorm:"column:bind_active;not null;default:b'0';comment:是否激活(BOOL):0-未激活;1-激活" json:"bind_active"`        // 是否激活(BOOL):0-未激活;1-激活
}

// TableName AccountUserBindConnect's table name
func (*AccountUserBindConnect) TableName() string {
	return TableNameAccountUserBindConnect
}
