// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameAccountUserTagGroup = "account_user_tag_group"

// AccountUserTagGroup 标签分组表
type AccountUserTagGroup struct {
	TagGroupID      int32     `gorm:"column:tag_group_id;primaryKey;autoIncrement:true;comment:分组编号" json:"tag_group_id"`                  // 分组编号
	TagGroupName    string    `gorm:"column:tag_group_name;not null;comment:分组名称" json:"tag_group_name"`                                   // 分组名称
	TagGroupSort    int32     `gorm:"column:tag_group_sort;not null;default:255;comment:分组排序:从小到大" json:"tag_group_sort"`                  // 分组排序:从小到大
	TagGroupEnable  []uint8   `gorm:"column:tag_group_enable;not null;default:b'1';comment:是否有效(BOOL):0-禁用;1-启用" json:"tag_group_enable"`  // 是否有效(BOOL):0-禁用;1-启用
	TagGroupBuildin []uint8   `gorm:"column:tag_group_buildin;not null;default:b'0';comment:系统内置(BOOL):1-是; 0-否" json:"tag_group_buildin"` // 系统内置(BOOL):1-是; 0-否
	UpdateTime      time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"`               // 更新时间
	CreateTime      time.Time `gorm:"column:create_time;not null;comment:添加时间" json:"create_time"`                                         // 添加时间
}

// TableName AccountUserTagGroup's table name
func (*AccountUserTagGroup) TableName() string {
	return TableNameAccountUserTagGroup
}
