// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameAccountUserBlock = "account_user_block"

// AccountUserBlock 用户黑名单表
type AccountUserBlock struct {
	UserBlackID   int32 `gorm:"column:user_black_id;primaryKey;autoIncrement:true;comment:黑名单编号" json:"user_black_id"` // 黑名单编号
	UserID        int32 `gorm:"column:user_id;not null;comment:用户编号" json:"user_id"`                                   // 用户编号
	BlackID       int32 `gorm:"column:black_id;not null;comment:拉黑用户编号" json:"black_id"`                               // 拉黑用户编号
	UserBlackTime int64 `gorm:"column:user_black_time;not null;comment:拉黑时间" json:"user_black_time"`                   // 拉黑时间
}

// TableName AccountUserBlock's table name
func (*AccountUserBlock) TableName() string {
	return TableNameAccountUserBlock
}
