// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameAccountUserBase = "account_user_base"

// AccountUserBase 用户基本信息表
type AccountUserBase struct {
	UserID       int32  `gorm:"column:user_id;primaryKey;autoIncrement:true;comment:用户编号" json:"user_id"` // 用户编号
	UserAccount  string `gorm:"column:user_account;not null;comment:用户账号" json:"user_account"`            // 用户账号
	UserPassword string `gorm:"column:user_password;not null;comment:用户密码" json:"user_password"`          // 用户密码
	UserSalt     string `gorm:"column:user_salt;not null;comment:salt值" json:"user_salt"`                 // salt值
}

// TableName AccountUserBase's table name
func (*AccountUserBase) TableName() string {
	return TableNameAccountUserBase
}
