// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameAccountUserGroup = "account_user_group"

// AccountUserGroup 好友管理组
type AccountUserGroup struct {
	GroupID   int32  `gorm:"column:group_id;primaryKey;autoIncrement:true;comment:好友组编号" json:"group_id"`                              // 好友组编号
	GroupName string `gorm:"column:group_name;not null;comment:组名称" json:"group_name"`                                                 // 组名称
	GroupType int32  `gorm:"column:group_type;not null;comment:群组类型(ENUM):0-临时组上限100人;  1-普通组上限300人; 2-VIP组 上限500人" json:"group_type"` // 群组类型(ENUM):0-临时组上限100人;  1-普通组上限300人; 2-VIP组 上限500人
	UserID    int32  `gorm:"column:user_id;not null;comment:管理员" json:"user_id"`                                                       // 管理员
	GroupNum  int32  `gorm:"column:group_num;not null;comment:数量" json:"group_num"`                                                    // 数量
}

// TableName AccountUserGroup's table name
func (*AccountUserGroup) TableName() string {
	return TableNameAccountUserGroup
}
