// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameAccountUserInfo = "account_user_info"

// AccountUserInfo 用户详细信息表
type AccountUserInfo struct {
	UserID               int32     `gorm:"column:user_id;primaryKey;autoIncrement:true;comment:用户编号" json:"user_id"`                                                      // 用户编号
	UserAccount          string    `gorm:"column:user_account;not null;comment:用户账号" json:"user_account"`                                                                 // 用户账号
	UserNickname         string    `gorm:"column:user_nickname;not null;comment:用户昵称" json:"user_nickname"`                                                               // 用户昵称
	UserAvatar           string    `gorm:"column:user_avatar;not null;comment:用户头像" json:"user_avatar"`                                                                   // 用户头像
	UserState            int32     `gorm:"column:user_state;not null;default:1;comment:状态(ENUM):0-锁定;1-已激活;2-未激活;" json:"user_state"`                                     // 状态(ENUM):0-锁定;1-已激活;2-未激活;
	UserMobile           string    `gorm:"column:user_mobile;not null;comment:手机号码(mobile)" json:"user_mobile"`                                                           // 手机号码(mobile)
	UserIntl             string    `gorm:"column:user_intl;not null;default:+86;comment:国家编码" json:"user_intl"`                                                           // 国家编码
	UserGender           int32     `gorm:"column:user_gender;not null;default:1;comment:性别(ENUM):0-保密;1-男;  2-女;" json:"user_gender"`                                     // 性别(ENUM):0-保密;1-男;  2-女;
	UserBirthday         time.Time `gorm:"column:user_birthday;not null;default:2000-01-01;comment:生日(DATE)" json:"user_birthday"`                                        // 生日(DATE)
	UserEmail            string    `gorm:"column:user_email;not null;comment:用户邮箱(email)" json:"user_email"`                                                              // 用户邮箱(email)
	UserLevelID          int32     `gorm:"column:user_level_id;not null;comment:等级编号" json:"user_level_id"`                                                               // 等级编号
	UserRealname         string    `gorm:"column:user_realname;not null;comment:真实姓名" json:"user_realname"`                                                               // 真实姓名
	UserIdcard           string    `gorm:"column:user_idcard;not null;comment:身份证" json:"user_idcard"`                                                                    // 身份证
	UserIdcardImages     string    `gorm:"column:user_idcard_images;not null;comment:身份证图片(DTO)" json:"user_idcard_images"`                                               // 身份证图片(DTO)
	UserIsAuthentication int32     `gorm:"column:user_is_authentication;not null;comment:认证状态(ENUM):0-未认证;1-待审核;2-认证通过;3-认证失败" json:"user_is_authentication"`             // 认证状态(ENUM):0-未认证;1-待审核;2-认证通过;3-认证失败
	TagIds               string    `gorm:"column:tag_ids;not null;comment:用户标签(DOT)" json:"tag_ids"`                                                                      // 用户标签(DOT)
	UserFrom             int32     `gorm:"column:user_from;not null;default:2310;comment:用户来源(ENUM):2310-其它;2311-pc;2312-H5;2313-APP;2314-小程序;2315-公众号" json:"user_from"` // 用户来源(ENUM):2310-其它;2311-pc;2312-H5;2313-APP;2314-小程序;2315-公众号
	UserNew              []uint8   `gorm:"column:user_new;not null;default:b'1';comment:新人标识(BOOL):0-不是;1-是" json:"user_new"`                                             // 新人标识(BOOL):0-不是;1-是
}

// TableName AccountUserInfo's table name
func (*AccountUserInfo) TableName() string {
	return TableNameAccountUserInfo
}
