// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameAccountUserMessage = "account_user_message"

// AccountUserMessage 短消息-聊天记录
type AccountUserMessage struct {
	MessageID         int32   `gorm:"column:message_id;primaryKey;autoIncrement:true;comment:消息编号" json:"message_id"`                                                              // 消息编号
	MessageParentID   int32   `gorm:"column:message_parent_id;not null;comment:上级编号" json:"message_parent_id"`                                                                     // 上级编号
	UserID            int32   `gorm:"column:user_id;not null;default:1;comment:所属用户:发送者或者接收者，如果message_kind=1则为当前用户发送的消息。" json:"user_id"`                                         // 所属用户:发送者或者接收者，如果message_kind=1则为当前用户发送的消息。
	UserNickname      string  `gorm:"column:user_nickname;not null;comment:用户昵称" json:"user_nickname"`                                                                             // 用户昵称
	MessageKind       int32   `gorm:"column:message_kind;not null;default:1;comment:消息种类(ENUM):1-发送消息;2-接收消息" json:"message_kind"`                                                 // 消息种类(ENUM):1-发送消息;2-接收消息
	UserOtherID       int32   `gorm:"column:user_other_id;not null;comment:相关用户:发送者或者接收者" json:"user_other_id"`                                                                    // 相关用户:发送者或者接收者
	UserOtherNickname string  `gorm:"column:user_other_nickname;not null;comment:相关昵称:发送者或者接收者" json:"user_other_nickname"`                                                        // 相关昵称:发送者或者接收者
	MessageTitle      string  `gorm:"column:message_title;not null;comment:消息标题" json:"message_title"`                                                                             // 消息标题
	MessageContent    string  `gorm:"column:message_content;not null;comment:消息内容" json:"message_content"`                                                                         // 消息内容
	MessageTime       int64   `gorm:"column:message_time;not null;comment:发送时间" json:"message_time"`                                                                               // 发送时间
	MessageIsRead     []uint8 `gorm:"column:message_is_read;not null;default:b'0';comment:是否读取(BOOL):0-未读;1-已读" json:"message_is_read"`                                            // 是否读取(BOOL):0-未读;1-已读
	MessageIsDelete   []uint8 `gorm:"column:message_is_delete;not null;default:b'0';comment:是否删除(BOOL):0-正常状态;1-删除状态" json:"message_is_delete"`                                    // 是否删除(BOOL):0-正常状态;1-删除状态
	MessageType       int32   `gorm:"column:message_type;not null;default:2;comment:消息类型(ENUM):1-系统消息;2-用户消息" json:"message_type"`                                                 // 消息类型(ENUM):1-系统消息;2-用户消息
	MessageCat        string  `gorm:"column:message_cat;not null;default:text;comment:消息类型(ENUM):text-文本消息;img-图片消息;video-视频消息;file:文件;location:位置;redpack:红包" json:"message_cat"` // 消息类型(ENUM):text-文本消息;img-图片消息;video-视频消息;file:文件;location:位置;redpack:红包
	MessageDataType   int32   `gorm:"column:message_data_type;not null;comment:消息分类(ENUM):0-默认消息;1-公告消息;2-订单消息;3-商品消息;4-余额卡券;5-服务消息" json:"message_data_type"`                     // 消息分类(ENUM):0-默认消息;1-公告消息;2-订单消息;3-商品消息;4-余额卡券;5-服务消息
	MessageDataID     string  `gorm:"column:message_data_id;not null;comment:消息数据:商品编号|订单编号" json:"message_data_id"`                                                               // 消息数据:商品编号|订单编号
	MessageLength     int32   `gorm:"column:message_length;not null;comment:消息长度" json:"message_length"`                                                                           // 消息长度
	MessageW          int32   `gorm:"column:message_w;not null;comment:图片宽度" json:"message_w"`                                                                                     // 图片宽度
	MessageH          int32   `gorm:"column:message_h;not null;comment:图片高度" json:"message_h"`                                                                                     // 图片高度
}

// TableName AccountUserMessage's table name
func (*AccountUserMessage) TableName() string {
	return TableNameAccountUserMessage
}
