// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameAccountUserChannel = "account_user_channel"

// AccountUserChannel 用户渠道表
type AccountUserChannel struct {
	UserChannelID      int32  `gorm:"column:user_channel_id;primaryKey;autoIncrement:true;comment:渠道编号" json:"user_channel_id"`       // 渠道编号
	UserChannelName    string `gorm:"column:user_channel_name;not null;comment:渠道名称" json:"user_channel_name"`                        // 渠道名称
	UserChannelPrefix  string `gorm:"column:user_channel_prefix;not null;comment:渠道前缀" json:"user_channel_prefix"`                    // 渠道前缀
	UserChannelEnable  int32  `gorm:"column:user_channel_enable;not null;comment:是否启用(BOOL):0-禁用;1-启用" json:"user_channel_enable"`    // 是否启用(BOOL):0-禁用;1-启用
	UserChannelBuildin int32  `gorm:"column:user_channel_buildin;not null;comment:是否内置(BOOL):0-非内置;1-内置" json:"user_channel_buildin"` // 是否内置(BOOL):0-非内置;1-内置
}

// TableName AccountUserChannel's table name
func (*AccountUserChannel) TableName() string {
	return TableNameAccountUserChannel
}
