// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameAccountUserTagBase = "account_user_tag_base"

// AccountUserTagBase 用户标签表
type AccountUserTagBase struct {
	TagID      int32   `gorm:"column:tag_id;primaryKey;autoIncrement:true;comment:标签编码" json:"tag_id"`                  // 标签编码
	TagTitle   string  `gorm:"column:tag_title;not null;comment:标签标题" json:"tag_title"`                                 // 标签标题
	TagGroupID int32   `gorm:"column:tag_group_id;not null;comment:所属分类" json:"tag_group_id"`                           // 所属分类
	TagSort    int32   `gorm:"column:tag_sort;not null;default:255;comment:配置排序:从小到大" json:"tag_sort"`                  // 配置排序:从小到大
	TagEnable  []uint8 `gorm:"column:tag_enable;not null;default:b'1';comment:是否启用(BOOL):0-禁用;1-启用" json:"tag_enable"`  // 是否启用(BOOL):0-禁用;1-启用
	TagBuildin []uint8 `gorm:"column:tag_buildin;not null;default:b'0';comment:系统内置(BOOL):1-是; 0-否" json:"tag_buildin"` // 系统内置(BOOL):1-是; 0-否
}

// TableName AccountUserTagBase's table name
func (*AccountUserTagBase) TableName() string {
	return TableNameAccountUserTagBase
}
