// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameAccountUserFriend = "account_user_friend"

// AccountUserFriend 用户好友关系表
type AccountUserFriend struct {
	UserFriendID      int32  `gorm:"column:user_friend_id;primaryKey;autoIncrement:true" json:"user_friend_id"`
	UserID            int32  `gorm:"column:user_id;not null;comment:用户编号" json:"user_id"`                                         // 用户编号
	FriendID          int32  `gorm:"column:friend_id;not null;comment:好友编号" json:"friend_id"`                                     // 好友编号
	FriendNote        string `gorm:"column:friend_note;not null;comment:备注名称" json:"friend_note"`                                 // 备注名称
	UserFriendAddtime int64  `gorm:"column:user_friend_addtime;not null;comment:添加时间" json:"user_friend_addtime"`                 // 添加时间
	FriendState       int32  `gorm:"column:friend_state;not null;default:1;comment:关注状态(ENUM):1-单向关注;2-双向关注" json:"friend_state"` // 关注状态(ENUM):1-单向关注;2-双向关注
	FriendInvite      int32  `gorm:"column:friend_invite;not null;comment:邀请状态(ENUM):0-新邀请;2-处理完成后邀请" json:"friend_invite"`       // 邀请状态(ENUM):0-新邀请;2-处理完成后邀请
}

// TableName AccountUserFriend's table name
func (*AccountUserFriend) TableName() string {
	return TableNameAccountUserFriend
}
