// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameAccountUserHistory = "account_user_history"

// AccountUserHistory 用户密码历史信息表
type AccountUserHistory struct {
	UserID              int32  `gorm:"column:user_id;primaryKey;comment:用户编号" json:"user_id"`                           // 用户编号
	UserHistoryPassword string `gorm:"column:user_history_password;not null;comment:历史密码" json:"user_history_password"` // 历史密码
	UserHistoryIP       string `gorm:"column:user_history_ip;not null;comment:历史 IP" json:"user_history_ip"`            // 历史 IP
	UserHistoryTime     int64  `gorm:"column:user_history_time;not null;comment:修改时间" json:"user_history_time"`         // 修改时间
}

// TableName AccountUserHistory's table name
func (*AccountUserHistory) TableName() string {
	return TableNameAccountUserHistory
}
