// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameAccountUserLevelLog = "account_user_level_log"

// AccountUserLevelLog 用户等级记录表
type AccountUserLevelLog struct {
	UserLevelLogID int32  `gorm:"column:user_level_log_id;primaryKey;autoIncrement:true;comment:日志编号" json:"user_level_log_id"` // 日志编号
	UserID         int32  `gorm:"column:user_id;not null;comment:用户编号" json:"user_id"`                                          // 用户编号
	UserLevelID    int32  `gorm:"column:user_level_id;not null;comment:当前等级ID" json:"user_level_id"`                            // 当前等级ID
	UserLevelPreID int32  `gorm:"column:user_level_pre_id;not null;comment:之前等级ID" json:"user_level_pre_id"`                    // 之前等级ID
	OperateRemark  string `gorm:"column:operate_remark;not null;comment:操作备注" json:"operate_remark"`                            // 操作备注
	OperateUserID  int32  `gorm:"column:operate_user_id;not null;comment:操作人" json:"operate_user_id"`                           // 操作人
	CreateTime     int64  `gorm:"column:create_time;not null;comment:操作时间" json:"create_time"`                                  // 操作时间
}

// TableName AccountUserLevelLog's table name
func (*AccountUserLevelLog) TableName() string {
	return TableNameAccountUserLevelLog
}
