// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameAccountUserLogin = "account_user_login"

// AccountUserLogin 用户登录信息表
type AccountUserLogin struct {
	UserID            int32     `gorm:"column:user_id;primaryKey;comment:用户编号" json:"user_id"`                         // 用户编号
	UserActiveTime    int64     `gorm:"column:user_active_time;not null;comment:激活时间" json:"user_active_time"`         // 激活时间
	UserRegIP         string    `gorm:"column:user_reg_ip;not null;comment:注册IP" json:"user_reg_ip"`                   // 注册IP
	UserRegDate       time.Time `gorm:"column:user_reg_date;not null;comment:注册日期" json:"user_reg_date"`               // 注册日期
	UserRegTime       int64     `gorm:"column:user_reg_time;not null;comment:注册时间" json:"user_reg_time"`               // 注册时间
	UserCountLogin    int32     `gorm:"column:user_count_login;not null;comment:登录次数" json:"user_count_login"`         // 登录次数
	UserLastloginIP   string    `gorm:"column:user_lastlogin_ip;not null;comment:上次登录IP" json:"user_lastlogin_ip"`     // 上次登录IP
	UserLastloginTime int64     `gorm:"column:user_lastlogin_time;not null;comment:上次登录时间" json:"user_lastlogin_time"` // 上次登录时间
	UserClientid      string    `gorm:"column:user_clientid;not null;comment:APPCID(DOT)" json:"user_clientid"`        // APPCID(DOT)
}

// TableName AccountUserLogin's table name
func (*AccountUserLogin) TableName() string {
	return TableNameAccountUserLogin
}
