// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameAccountUserInvoice = "account_user_invoice"

// AccountUserInvoice 用户发票管理表
type AccountUserInvoice struct {
	UserInvoiceID         int32     `gorm:"column:user_invoice_id;primaryKey;autoIncrement:true;comment:发票编号" json:"user_invoice_id"`                         // 发票编号
	UserID                int32     `gorm:"column:user_id;not null;comment:所属用户" json:"user_id"`                                                              // 所属用户
	InvoiceTitle          string    `gorm:"column:invoice_title;not null;comment:发票抬头" json:"invoice_title"`                                                  // 发票抬头
	InvoiceCompanyCode    string    `gorm:"column:invoice_company_code;not null;comment:纳税人识别号" json:"invoice_company_code"`                                  // 纳税人识别号
	InvoiceContent        string    `gorm:"column:invoice_content;not null;comment:发票内容" json:"invoice_content"`                                              // 发票内容
	InvoiceIsCompany      []uint8   `gorm:"column:invoice_is_company;not null;default:b'1';comment:公司开票(BOOL):0-个人;1-公司" json:"invoice_is_company"`           // 公司开票(BOOL):0-个人;1-公司
	InvoiceIsElectronic   []uint8   `gorm:"column:invoice_is_electronic;not null;default:b'1';comment:电子发票(ENUM):0-纸质发票;1-电子发票" json:"invoice_is_electronic"` // 电子发票(ENUM):0-纸质发票;1-电子发票
	InvoiceType           int32     `gorm:"column:invoice_type;not null;default:1;comment:发票类型(ENUM):1-普通发票;2-增值税专用发票" json:"invoice_type"`                   // 发票类型(ENUM):1-普通发票;2-增值税专用发票
	InvoiceDatetime       time.Time `gorm:"column:invoice_datetime;not null;default:CURRENT_TIMESTAMP;comment:添加时间" json:"invoice_datetime"`                  // 添加时间
	InvoiceAddress        string    `gorm:"column:invoice_address;not null;comment:单位地址" json:"invoice_address"`                                              // 单位地址
	InvoicePhone          string    `gorm:"column:invoice_phone;not null;comment:单位电话" json:"invoice_phone"`                                                  // 单位电话
	InvoiceBankname       string    `gorm:"column:invoice_bankname;not null;comment:开户银行" json:"invoice_bankname"`                                            // 开户银行
	InvoiceBankaccount    string    `gorm:"column:invoice_bankaccount;not null;comment:银行账号" json:"invoice_bankaccount"`                                      // 银行账号
	InvoiceContactMobile  string    `gorm:"column:invoice_contact_mobile;not null;comment:收票人手机" json:"invoice_contact_mobile"`                               // 收票人手机
	InvoiceContactEmail   string    `gorm:"column:invoice_contact_email;not null;comment:收票人邮箱" json:"invoice_contact_email"`                                 // 收票人邮箱
	InvoiceIsDefault      bool      `gorm:"column:invoice_is_default;not null;comment:是否默认" json:"invoice_is_default"`                                        // 是否默认
	InvoiceContactName    string    `gorm:"column:invoice_contact_name;not null;comment:收票人" json:"invoice_contact_name"`                                     // 收票人
	InvoiceContactArea    string    `gorm:"column:invoice_contact_area;not null;comment:收票人地区" json:"invoice_contact_area"`                                   // 收票人地区
	InvoiceContactAddress string    `gorm:"column:invoice_contact_address;not null;comment:收票详细地址" json:"invoice_contact_address"`                            // 收票详细地址
}

// TableName AccountUserInvoice's table name
func (*AccountUserInvoice) TableName() string {
	return TableNameAccountUserInvoice
}
